version: '3.9'
services:
  app:
    build: 
      context: .
    environment:
      - DATABASE_URL=${DATABASE_URL}
    restart : always
    depends_on:
      - db
    ports:
      - 4500:3000
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - .:/src
      - uploaded_files:/usr/src/app/uploads

  db:
    image: postgres:16.0
    restart: always
    ports:
      - 6500:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend
volumes:
  postgres_data:
  uploaded_files:
networks:
  backend:
